#!/bin/sh

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$1" in
  start)
  exec forever --spinSleepTime 10000 --sourceDir=/var/domothink -p /var/run/forever start dist/server.js
  ;;

  stop)
  exec forever stop --sourceDir=/var/domothink dist/server.js
  ;;

  status)
  # TODO
  ;;

  default)
  # TODO
  ;;
esac

exit 0
